runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  PROJECT_ID: "My First Project"

env: flex



handlers:
- url: /.*
  script: auto

service: my-app-service  # Replace with your desired service name
